[2025-04-16T16:45:59.745+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T16:45:59.753+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-16T16:45:59.758+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-16T16:45:59.759+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T16:45:59.769+0300] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2025-04-13 00:00:00+00:00
[2025-04-16T16:45:59.771+0300] {standard_task_runner.py:72} INFO - Started process 177683 to run task
[2025-04-16T16:45:59.774+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_Branching_tasks_with_Backfill', 'branch_task', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/execute_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpvudof637']
[2025-04-16T16:45:59.776+0300] {standard_task_runner.py:105} INFO - Job 144: Subtask branch_task
[2025-04-16T16:45:59.800+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task scheduled__2025-04-13T00:00:00+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T16:45:59.843+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_Branching_tasks_with_Backfill' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-16T16:45:59.844+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T16:45:59.854+0300] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-16T16:45:59.858+0300] {python.py:240} INFO - Done. Returned value was: task_c
[2025-04-16T16:45:59.859+0300] {branch.py:38} INFO - Branch into task_c
[2025-04-16T16:45:59.859+0300] {skipmixin.py:233} INFO - Following branch ('task_c',)
[2025-04-16T16:45:59.861+0300] {skipmixin.py:281} INFO - Skipping tasks [('task_d', -1)]
[2025-04-16T16:45:59.880+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T16:45:59.880+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_Python_Branching_tasks_with_Backfill, task_id=branch_task, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250416T134559, end_date=20250416T134559
[2025-04-16T16:45:59.914+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T16:45:59.924+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T16:45:59.928+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
