[2025-04-16T14:10:03.082+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T14:10:03.099+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks.branch_task manual__2025-04-16T11:09:58.556360+00:00 [queued]>
[2025-04-16T14:10:03.106+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks.branch_task manual__2025-04-16T11:09:58.556360+00:00 [queued]>
[2025-04-16T14:10:03.106+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T14:10:03.124+0300] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2025-04-16 11:09:58.556360+00:00
[2025-04-16T14:10:03.127+0300] {standard_task_runner.py:72} INFO - Started process 113057 to run task
[2025-04-16T14:10:03.130+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_Branching_tasks', 'branch_task', 'manual__2025-04-16T11:09:58.556360+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/execute_branching.py', '--cfg-path', '/tmp/tmpqx_x82i5']
[2025-04-16T14:10:03.132+0300] {standard_task_runner.py:105} INFO - Job 126: Subtask branch_task
[2025-04-16T14:10:03.169+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_Branching_tasks.branch_task manual__2025-04-16T11:09:58.556360+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T14:10:03.224+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_Branching_tasks' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T11:09:58.556360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T11:09:58.556360+00:00'
[2025-04-16T14:10:03.225+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T14:10:03.237+0300] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-16T14:10:03.241+0300] {python.py:240} INFO - Done. Returned value was: not_eligible_for_license
[2025-04-16T14:10:03.241+0300] {branch.py:38} INFO - Branch into not_eligible_for_license
[2025-04-16T14:10:03.242+0300] {skipmixin.py:233} INFO - Following branch ('not_eligible_for_license',)
[2025-04-16T14:10:03.247+0300] {skipmixin.py:281} INFO - Skipping tasks [('eligible_for_license', -1)]
[2025-04-16T14:10:03.265+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T14:10:03.266+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_Python_Branching_tasks, task_id=branch_task, run_id=manual__2025-04-16T11:09:58.556360+00:00, execution_date=20250416T110958, start_date=20250416T111003, end_date=20250416T111003
[2025-04-16T14:10:03.320+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T14:10:03.347+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T14:10:03.353+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
