[2025-04-16T13:16:57.687+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T13:16:57.704+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sqlite_pipeline.insert_data_1 manual__2025-04-16T10:16:52.793737+00:00 [queued]>
[2025-04-16T13:16:57.711+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sqlite_pipeline.insert_data_1 manual__2025-04-16T10:16:52.793737+00:00 [queued]>
[2025-04-16T13:16:57.711+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T13:16:57.734+0300] {taskinstance.py:2890} INFO - Executing <Task(SqliteOperator): insert_data_1> on 2025-04-16 10:16:52.793737+00:00
[2025-04-16T13:16:57.739+0300] {standard_task_runner.py:72} INFO - Started process 91107 to run task
[2025-04-16T13:16:57.747+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sqlite_pipeline', 'insert_data_1', 'manual__2025-04-16T10:16:52.793737+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/sql_operators.py', '--cfg-path', '/tmp/tmpm2qww7yp']
[2025-04-16T13:16:57.752+0300] {standard_task_runner.py:105} INFO - Job 106: Subtask insert_data_1
[2025-04-16T13:16:57.804+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_sqlite_pipeline.insert_data_1 manual__2025-04-16T10:16:52.793737+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T13:16:57.885+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_sqlite_pipeline' AIRFLOW_CTX_TASK_ID='insert_data_1' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T10:16:52.793737+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T10:16:52.793737+00:00'
[2025-04-16T13:16:57.886+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T13:16:57.909+0300] {sql.py:266} INFO - Executing: 
        INSERT INTO users (name, age, is_active) VALUES
        ('John Doe', 30, True),
        ('Jane Smith', 25, True),
        ('Alice Johnson', 28, True),
        ('Bob Brown', 35, False),
        ('Charlie Black', 22, True);
        
[2025-04-16T13:16:57.920+0300] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-04-16T13:16:57.944+0300] {base.py:84} INFO - Retrieving connection 'my_sqlite_conn'
[2025-04-16T13:16:57.945+0300] {sql.py:542} INFO - Running statement: 
        INSERT INTO users (name, age, is_active) VALUES
        ('John Doe', 30, True),
        ('Jane Smith', 25, True),
        ('Alice Johnson', 28, True),
        ('Bob Brown', 35, False),
        ('Charlie Black', 22, True);
        , parameters: None
[2025-04-16T13:16:57.946+0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 487, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 547, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: table users has no column named is_active
[2025-04-16T13:16:57.956+0300] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=executing_sqlite_pipeline, task_id=insert_data_1, run_id=manual__2025-04-16T10:16:52.793737+00:00, execution_date=20250416T101652, start_date=20250416T101657, end_date=20250416T101657
[2025-04-16T13:16:57.987+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T13:16:57.988+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 106 for task insert_data_1 (table users has no column named is_active; 91107)
Traceback (most recent call last):
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 487, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/tasneemahmed24/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 547, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: table users has no column named is_active
[2025-04-16T13:16:58.020+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-16T13:16:58.040+0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T13:16:58.047+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
