[2025-04-16T16:46:04.496+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T16:46:04.507+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-16T16:46:04.515+0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-16T16:46:04.516+0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-16T16:46:04.530+0300] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2025-04-14 00:00:00+00:00
[2025-04-16T16:46:04.533+0300] {standard_task_runner.py:72} INFO - Started process 177732 to run task
[2025-04-16T16:46:04.536+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_Python_Branching_tasks_with_Backfill', 'branch_task', 'scheduled__2025-04-14T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/execute_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmp5st_3a1v']
[2025-04-16T16:46:04.538+0300] {standard_task_runner.py:105} INFO - Job 147: Subtask branch_task
[2025-04-16T16:46:04.571+0300] {task_command.py:467} INFO - Running <TaskInstance: executing_Python_Branching_tasks_with_Backfill.branch_task scheduled__2025-04-14T00:00:00+00:00 [running]> on host DESKTOP-1SBO1JU.
[2025-04-16T16:46:04.625+0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tasneemahmed' AIRFLOW_CTX_DAG_ID='executing_Python_Branching_tasks_with_Backfill' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T00:00:00+00:00'
[2025-04-16T16:46:04.626+0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-16T16:46:04.634+0300] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-16T16:46:04.637+0300] {python.py:240} INFO - Done. Returned value was: task_d
[2025-04-16T16:46:04.637+0300] {branch.py:38} INFO - Branch into task_d
[2025-04-16T16:46:04.638+0300] {skipmixin.py:233} INFO - Following branch ('task_d',)
[2025-04-16T16:46:04.641+0300] {skipmixin.py:281} INFO - Skipping tasks [('task_c', -1)]
[2025-04-16T16:46:04.659+0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-16T16:46:04.659+0300] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_Python_Branching_tasks_with_Backfill, task_id=branch_task, run_id=scheduled__2025-04-14T00:00:00+00:00, execution_date=20250414T000000, start_date=20250416T134604, end_date=20250416T134604
[2025-04-16T16:46:04.717+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T16:46:04.728+0300] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-16T16:46:04.733+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
